# Generated by Django 5.0.7 on 2024-08-13 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
