# Generated by Django 5.0.7 on 2024-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_customuser_age_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
