# Generated by Django 5.0.7 on 2024-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursecategory_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
