# Generated by Django 5.0.7 on 2024-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
