# Generated by Django 5.0.7 on 2024-08-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_enrollment_date_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
