# Generated by Django 5.0.7 on 2024-08-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_lecture_course_alter_lecture_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video_url',
        ),
    ]
